export const servicesConstants = {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

    GET_SUB_CATEGORIES_REQUEST: 'GET_SUB_CATEGORIES_REQUEST',
    GET_SUB_CATEGORIES_SUCCESS: 'GET_SUB_CATEGORIES_SUCCESS',
    GET_SUB_CATEGORIES_FAILURE: 'GET_SUB_CATEGORIES_FAILURE',
};